#!/bin/bash

DOTFILES_HOME=$HOME/.dotfiles

# http://stackoverflow.com/a/11512211
dir_to_755() {
    find ./ -type d -exec chmod 755 {} \;
}
files_to_644() {
    find /opt/lampp/htdocs -type f -exec chmod 644 {} \;
}

alias vim=nvim

alias cls='clear; ls'
alias sadd='ssh-add'
alias serve='sudo nginx'
alias pc='sudo bash $DOTFILES_HOME/scripts/portcheck.sh'
alias ccadd="ccollab addgitdiffs"
alias ffpriv='firefox -new-instance -private &'
alias killorig='find . -depth -name "*.orig" -type f -delete'

alias dck='sudo docker'
alias dck-remoteuntagged='dck images -q --filter "dangling=true" | xargs sudo docker rmi -f'
alias dck-runsite='sudo docker run -it --net=host personal-site'
#http://stackoverflow.com/questions/17903705/is-it-possible-to-start-a-shell-session-in-a-running-container-without-ssh
#docker run --name ubuntu_bash --rm -i -t ubuntu bash

# in my $HOME/.gitconfig in [alias] section:
# tclean = clean -f -x -d --exclude 'node_modules'
alias git-reset='git tclean; git reset --hard; git sub init; git sub update; git sub foreach --recursive "git tclean; git reset --hard; git sub init; git sub update; git-reset;";'

# Adapted from http://superuser.com/a/39780
alias inPath="echo $PATH | tr ':' '\n' | grep -x -c >/dev/null"
alias countInPath="echo $PATH | tr ':' '\n' | grep -x -c"

alias morningRoutine="git fetch && tig --all --author-date-order --no-merges"
alias mr=morningRoutine

alias use-real-scrollbars='gsettings set com.canonical.desktop.interface scrollbar-mode normal'
alias use-default-scrollbars='gsettings reset com.canonical.desktop.interface scrollbar-mode'

alias killxsel="pkill -c xsel"
alias kx=killxsel

alias cripple_zeitgeist='chmod -rw ~/.local/share/zeitgeist/activity.sqlite && zeitgeist-daemon --replace'
alias restore_zeitgesit='chmod +rw ~/.local/share/zeitgeist/activity.sqlite && zeitgeist-daemon --replace'

alias dosuspend='systemctl suspend'

# don't know why this happens...
alias fixmouse="sudo modprobe -r psmouse && sudo modprobe psmouse"
alias fixwireless='sudo service network-manager restart'
alias fixunity='unity --reset-icons &disown'
alias fixdiff='export $(dbus-launch)'
alias fixdisplay='export DISPLAY=:0.0'
alias fixkdiff='fixdiff && fixdisplay'
alias fixssh='eval `ssh-agent -s`'

# Lets you do something like `command || err`
alias err='notify-send "Build Failed"'

