#!/bin/bash

branch_name="$(git symbolic-ref HEAD 2>/dev/null)" ||
branch_name="(unnamed branch)"     # detached HEAD

branch_name=${branch_name##refs/heads/}
echo Pushing branch: $branch_name

git log origin/$branch_name..$branch_name --pretty=format:%s

exit 1


